---

- hosts: all
  become: true
  tasks:
          - name: install apache and php support package
            package:
                    name:
                            - "{{ apache_package }}" 
                            - "{{ php_package }}"
                    state: latest
                    update_cache: yes

          - name: enable apache2
            systemd:
                    name: httpd
                    enabled: yes
                    state: started
            when: ansible_distribution_file_variety == "RedHat"

          - name: allow firewall on http
            firewalld:
                    port: 80/tcp
                    permanent: yes
                    immediate: yes
                    state: enabled
            when: ansible_distribution_file_variety == "RedHat"
