---

- hosts: all
  become: true
  tasks:
          - name: update repository index
            dnf:
                    update_cache: yes
            when: ansible_distribution_file_variety == "RedHat"

          - name: install apache2 package
            dnf:
                    name: httpd  
                    state: latest
            when: ansible_distribution_file_variety == "RedHat"
          - name: enable apache2
            systemd:
                    name: httpd
                    enabled: yes
                    state: started
            when: ansible_distribution_file_variety == "RedHat"

          - name: allow firewall on http
            firewalld:
                    port: 80/tcp
                    permanent: yes
                    immediate: yes
                    state: enabled
            when: ansible_distribution_file_variety == "RedHat"
          - name: add php support apache
            dnf:
                    name: php
                    state: latest
            when: ansible_distribution_file_variety == "RedHat"

          - name: update repository index
            apt:
                    update_cache: yes
            when: ansible_distribution_file_variety == "Debian"

          - name: install apache2 package
            apt:
                    name: apache2
                    state: latest
            when: ansible_distribution_file_variety == "Debian"

          - name: add php support for apache
            apt:
                    name: libapache2-mod-php
                    state: latest
            when: ansible_distribution_file_variety == "Debian"
