---

- hosts: all
  become: true
  tasks:
          - name: update repository index
            dnf:
                    update_cache: yes

          - name: install apache2 package
            dnf:
                    name: httpd  
                    state: latest
          - name: enable apache2
            systemd:
                    name: httpd
                    enabled: yes
                    state: started
