- name: install httpd package
  tags: apache,php
  package:
          name:
                  - "{{ apache_package }}"
                  - "{{ php_package }}"
          state: latest

- name: copy index file to webserver 
  tags: httpd,apache
  copy:
          src: files/default_site.html
          dest: /var/www/html/index.html
          owner: root
          group: root
          mode: 0644

- name: allow http connection through firewall (CentOS)
  tags: httpd,apache,centos,firewalld
  firewalld:
          port: 80/tcp
          permanent: yes
          immediate: yes
          state: enabled
  when: ansible_distribution_file_variety == "RedHat"
  
- name: chage admin email address (CentOS)
  tags: httpd,apache,centos
  lineinfile:
          path: /etc/httpd/conf/httpd.conf
          regexp: "^ServerAdmin"
          line: ServerAdmin jonhwalker@myhome.local
  when: ansible_distribution_file_variety == "RedHat"
  notify: restart_httpd
